### ISSUE TITLE
[error]'description' cannot be null

### ISSUE THREAD

**Issue by Orangen** [tangro/actions-deploy#2]
In Stella bekommen wir den Fehler `[error]'description' cannot be null` bei Deploy styleguide.

![image](https://user-images.githubusercontent.com/5445259/76765064-1dbe7d80-6796-11ea-94bf-6173d75fc12e.png)

@ankri 
Können wir die description in `setStatus` einfach auf leere string setzen wenn wir keine Daten haben ?
Oder müsste diese immer gefüllt sein,  und es gibt einen Fehler beim Aufruf ?

**Comment by ankri** [comment]
Nur als Info, weil ich ein bißchen gebraucht habe um zu verstehen was gemeint ist:

Die `action-deploy` versucht den ursprünglichen Status wiederherzustellen. Wenn einer da ist wird der Status und die `description` gesetzt. Beim Styleguide gibt es keine vorherige `description`.

Als Antwort:
Zeile 91: 
```diff
-        description: previousStatus ? previousStatus.description : undefined,
+       description: previousStatus ? previousStatus.description ?? '' : '',
```

**Comment by Orangen** [comment]
ja genau die stelle meinte ich. 
ok, dann passe ich das morgen an und release einen die 1.2.1 Version.

**Comment by ankri** [comment]
Mal schauen, eventuell schaffe ich es auch. Im selben Zug sollten wir `acorn` aktualisieren. Da gibts eine Security Warning.
